modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/Tazer-Y/Ablaze"
license="MIT"

[[mods]] #mandatory
modId="ablaze"
version="0.0a"
displayName="Create: Ablaze"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/Tazer-Y/Ablaze"
logoFile="ablaze.png"
credits="Thanks to our discord server members and contributors!"
authors="Tazer, Fortress Nebula"
description='''
Create: Ablaze is a mod that hopes to empower the player even more with the industrial age of the create mod and space rockets!'''

[[dependencies.ablaze]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ablaze]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ablaze]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.18-0.6.0]"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.ablaze]]
    modId="create"
    mandatory=true
    versionRange="[0.4d]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ablaze]]
    modId="alloyed"
    mandatory=false
    versionRange="[1.18.1-v1.2]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ablaze]]
modId="steampowered"
mandatory=false
versionRange="[1.18.1-2.0.0-alpha]"
ordering="AFTER"
side="BOTH"
