modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/Tazer-Y/Create-Liftoff/issues"
license="MIT"

[[mods]] #mandatory
modId="createliftoff"
version="0.0a"
displayName="Create: Liftoff"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/Tazer-Y/Create-Liftoff"
logoFile= "createliftoff.png"
credits="Thanks to our discord server members and contributors!"
authors="Tazer, Fortress Nebula"
description='''
Create: Liftoff is a mod that hopes to empower the player even more with the industrial age of the create mod and space rockets!
'''

[[dependencies.createliftoff]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createliftoff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createliftoff]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.18-0.6.2,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.createliftoff]]
    modId="create"
    mandatory=true
    versionRange="[0.4.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.createliftoff]]
    modId="alloyed"
    mandatory=false
    versionRange="[1.18.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.createliftoff]]
    modId="steampowered"
    mandatory=false
    versionRange="[1.18.1-2.0.0-alpha]"
    ordering="AFTER"
    side="BOTH"
